### ISSUE TITLE
api always null

### ISSUE THREAD

**Issue by woipot** [hanilozmen/Bumerang#1]
Bumerang bumerang = new Bumerang.Builder(context, BASE_URL).gson(new Gson()).build();
 MyBumerangAPI api = Bumerang.get().initAPI(MyBumerangAPI.class);

api always null
 it try to check yor sample, and have same problem

**Comment by hanilozmen** [comment]
Sample app works fine, I just tried it with this initialization -> 
Bumerang bumerang = new Bumerang.Builder(getApplicationContext(),"https://jsonplaceholder.typicode.com/").gson(new Gson()).build();

You may have problems with your BASE_URL or MyBumerangAPI.class 
Could you send them too?

You probably called this -> MyBumerangAPI api = Bumerang.get().initAPI(MyBumerangAPI.class);
before initializing the library with -> Bumerang bumerang = new Bumerang.Builder(context, BASE_URL).gson(new Gson()).build();

In the sample app Bumerang is initialized inside application class. So, it is called before any Activity onCreate methods.
I updated the sample app to make usage more clear. Please check it.

**Comment by hanilozmen** [comment]
I updated target sdk version to 30, gradle to 6.5. Updated library version to 1.0.1 since it was tested in production with high traffic. I also simplified the sample app. Please recheck it @woipot
